### ISSUE TITLE
server crashes after a while for no reason

### ISSUE THREAD

**Issue by Lyncesca** [drawpile/Drawpile#433]
using the actual server program rather than the built in hoster

it is as i say on the tin

**Comment by callaa** [comment]
If you're using version 2.0.0 or 2.0.1, it's probably the bug fixed by commit f88db72. At least drawpile.net's public server hasn't crashed once after I installed an update that included that fix. (The bug is triggered when closing a session with an active public announcement.) I will probably release 2.0.2 in about a week or so, after I've fixed a couple other bugs.

**Comment by Lyncesca** [comment]
still crashing, only now it's crashing whenever people join after a while

**Comment by callaa** [comment]
With 2.0.2? Are you using the graphical or the headless version of the server?

**Comment by greatzott** [comment]
Don't mean to piggyback, but I have tried hosting through the built-in and drawpile-srv and I have the same issue. It seems to happen after a certain period of time and then a new user attempting to login. I have been able to replicate the issue. Using 2.0.2 64 bit on windows 10

**Comment by Lyncesca** [comment]
i close the gui after i start the server from it. i believe it minimises to the taskbar after that.
2.0.2 64 bit on win 8.1

as far as i can tell my symptoms are identical to greatzott. after a period of time, the server crashes when a new user attempts to connect

**Comment by callaa** [comment]
Okay, I made some progress. I managed to replicate the crash once, but I don't know the exact steps yet. It may be possible that the server has to be idle for some time for the bug to manifest. That would explain why the public server hasn't crashed.

**Comment by callaa** [comment]
I haven't been able to make the server crash a second time yet, but I did discover a bug that can crash the server in certain specific circumstances. I made a new test build: https://drawpile.net/files/win/drawpile-srv-2.0.2.2.zip

Can you try if this version fixes the problem?

**Comment by greatzott** [comment]
So I tried out the test build and managed to get it to crash by the same means, but I noticed something interesting.
Before the crash I logged into the session on a second computer and I noticed some brush strokes were visible on the newly signed in client, but the brush stroke was removed on the session owner client. I closed out of Drawpile on the second computer and tried to log back in, and that is when the server crashed. My guess is that there is some sort of conflict with a client receiving the canvas? Not too knowledgeable on how drawpile works.

**Comment by callaa** [comment]
Hmm, I can't immediately think of an explanation why some strokes would not be visible on the original client.
At what point did the server crash? Did it crash immediately when connecting to the server or after joining the selected session? If the latter, did any of the session download before the server crashed?

I've been leaving the server running for several hours and I still haven't been able to make it crash again. Have you noticed if there's any specific steps you can take to trigger the crash?

**Comment by greatzott** [comment]
I did a quick recording of the issue. https://youtu.be/_ar5-DXVoJk
Some notes:
- The canvas will not show any loading progress on the entering client side, once that loading window appears the server crashes.
- The server was live for around 20 minutes and the session was live for about 10 minutes.
- It took 2 login attempts to get it to break, each 5 minutes apart. 
- The issue will arise regardless of any specific user.
- The brushstroke issue seems to be harder to reproduce.

**Comment by callaa** [comment]
Thanks. Narrowing down the possible locations of the bug based on the evidence so far:

 * Since it happens both with the built-in and dedicated server, the bug must be in the shared server code and not in the UI shells.
 * The built-in server always uses in-memory file history, while the dedicated GUI server defaults to file backed history, therefore the bug is not in the session history code
 * Occurs before entire history is uploaded, but after the login has completed: probably happens when client is assigned to a session

I've been running the server in a debugger and with valgrind, but haven't found an explanation yet. (I've found a couple of other bugs, though, but they don't appear to be related.)

I built a version of the server with debug symbols included: [drawpile-srv-2.0.2-debug.zip](https://drawpile.net/files/win/drawpile-srv-2.0.2-debug.zip)

Can you try running this version and sending me the crash dump after it has crashed? The crash dump can be generated in two ways (well, more but these are probably the easiest):

One way is to open the task manager, right click on the process (while the crash dialog is still open) and select "create dump file". This method produces ridiculously huge dumps, though.

Another way is to run this registry script: [enable-srv-crashdump.reg](https://drawpile.net/files/win/enable-srv-crashdump.reg)

It makes it so that when a `drawpile-srv.exe` process crashes, a minidump is written to `c:\dumps` (you can change the folder by editing the script.)

**Comment by greatzott** [comment]
So I got the dump files thanks to your reg script. I did a stream yesterday and had my viewers attempt to crash the server. Managed to get drawpile-srv to crash pretty much anytime someone logged in after around 15 minutes or so. 


[drawpile-srv Zott.zip](https://github.com/drawpile/Drawpile/files/908350/drawpile-srv.Zott.zip)

**Comment by callaa** [comment]
Thanks, that crash dump revealed the problem! The server thread runs out of stack space due to a very deeply recursive function call. The problem appears to be that when there are lots of (small) messages in the session history and a new user joins, the writeData function is called recursively until the output buffer is full or all messages are buffered for upload. It appears that the buffer is large enough that stack space runs out first. I'm not sure why this doesn't happen on the public server. Either the default stack size is larger on Linux, or the compiler doesn't do tail call optimization on Windows.

In any case, here's a new version that should fix the bug: https://drawpile.net/files/win/drawpile-srv-2.0.2.3.zip

**Comment by greatzott** [comment]
Thank you for the fix, I really appreciate. So far after an hour of usage, no crashes. 
If anything comes up I will contact you with a dump file. Thank you for your time.
