### ISSUE TITLE
Dedicated Server Crash when last user leaves

### ISSUE THREAD

**Issue by EgoEquus** [drawpile/Drawpile#748]
With the current version v2.1.7, I have started having an issue with the server crashing once the last user leaves a particular session.

So far with testing it happens under the following conditions:
1. Happens with a Persistent session
2. Session has been active for a few days with users coming and going normally.
3. Once it starts crashing, it is repeatable for that session. Always when the last user leaves.
4. Current fix is to save session to an .ora file on a client. Terminate the session. Then re-host it with a new ID.

Host for the Dedicated Server is
Windows 7 Ultimate x64 on Compaq Presario SR17171SL
Asus motherboard
AMD Sempron 3400+ 2.00GHz

**Comment by callaa** [comment]
I think this is probably the same bug that I just recently fixed in the master branch (afc30c83c4fd753a7849a6d574bbc11214e20899)

I think the bug is more easily triggered when running the server in GUI mode, which is probably why I hadn't noticed it before.

**Comment by EgoEquus** [comment]
Ahh, that's good to know. I guess I missed that article when I searched for recent server issues. I am guessing I should just leave the GUI off when not being used, until the next version is released.

**Comment by EgoEquus** [comment]
So I am still having this issue, even on the latest 2.1.10. I am running the server with the GUI. It is very consistent. Once a session starts crashing, even restarting the server does not help. Once a user leaves the session, it crashes. It does not matter if other users are still connected. I can fix it temporarily by recreating/rehosting the session.

Any ideas?

Here is the event 

Faulting application name: drawpile-srv.exe, version: 0.0.0.0, time stamp: 0x5ce109f7
Faulting module name: Qt5Network.dll, version: 5.12.2.0, time stamp: 0x5cac7f02
Exception code: 0xc0000005
Fault offset: 0x000000000009ada5
Faulting process id: 0x964
Faulting application start time: 0x01d51278b95cc9b6
Faulting application path: D:\Program Files\Drawpile\drawpile-srv.exe
Faulting module path: D:\Program Files\Drawpile\Qt5Network.dll
Report Id: 795d4972-81c7-11e9-a7d9-0015f250fee7

**Comment by Wade821** [comment]
Well, that error message clearly points to QT being the culprit. Problem with that is that QT patches and fixes are not within his ability to fix, as it is provided by another company. However, another open source program which relies on QT also (Krita) has done some excellent work on improving their product as well as finding bugs and reporting them to QT. The problem is that they must be reviewed and approved before being pushed out and available to everyone to use. So we're at the mercy of QT for a resolution at this point in time, as far as I can tell. 

https://krita.org/en/item/april-development-update/
![image](https://user-images.githubusercontent.com/18544575/59588142-cae75680-909b-11e9-9083-c4232a396513.png)

**Comment by notfood** [comment]
Is this still an issue?

**Comment by EgoEquus** [comment]
As of the last version I tried (2.1.10.0), it was still an issue. I had put this aside, so have not tried the latest version yet. I may do that this week. If it still crashes, I'll try a newer version of QT libraries. Thanks.

**Comment by EgoEquus** [comment]
Just updated clients and server. Same problem. Just not stable on my particular Windows 7 machine for some reason. May try the QT libraries as a last resort or a fresh operating system.

**Comment by MorrowShore** [comment]
Is this still happening?

**Comment by MorrowShore** [comment]
Issue cannot be reproduced as of now. Doesn't seem to be an issue anymore.
